# Generated by Django 6.0.7 on 2026-09-23 18:05 (hand-edited to add data migration)

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Give every existing product a unique slug derived from its name."""
    Product = apps.get_model('store', 'Product')
    seen = set()
    for product in Product.objects.all():
        base = slugify(product.name) or f'product-{product.id}'
        slug = base
        counter = 1
        while slug in seen or Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
            slug = f'{base}-{counter}'
            counter += 1
        product.slug = slug
        product.save(update_fields=['slug'])
        seen.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_active_product_stock_and_more'),
    ]

    operations = [
        # 1. Add non-required, non-unique fields first
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
        # 2. Add slug without unique constraint so existing rows can get ''
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, default=''),
        ),
        # 3. Data migration: fill in slugs for all existing products
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        # 4. Now that every row has a unique slug, add the unique constraint
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, blank=True),
        ),
    ]
